# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(max_length=30)),
                ('leve', models.CharField(max_length=30)),
                ('syst', models.CharField(max_length=30)),
                ('versio', models.CharField(max_length=30)),
                ('project', models.CharField(max_length=50)),
            ],
        ),
    ]
